knn:
  neighbors: [5, 10, 15, 20]
  validation_k: [5, 10, 15, 20, 25]

model_name: Neural Network
input_dim: 15
layers:
  - units: 64
    activation: relu
  - units: 32
    activation: relu
  - units: 1
    activation: sigmoid
optimizer: adam
loss: binary_crossentropy
metrics:
  - accuracy
  - recall
epochs: 50
batch_size: 32
class_weight:
  0: 1
  1: 3
early_stopping:
  monitor: val_recall
  patience: 5
  mode: max
  restore_best_weights: true
